language: java

dist: focal

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="fc5c05e1-66ef-49f4-ae04-370c917194a9"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kva.devops@gmail.com
    on_success: never
    on_failure: always